name: CI Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DIST_FILE: ivy-website-market.tar

jobs:
  build:
    runs-on: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          npm install

      - name: Run test
        run: |
          npm run test

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Karma Tests            # Name of the check run which will be created
          path: reports/karma-*.xml    # Path to test results
          reporter: karma-junit        # Format of test results

      - name: Clean up
        run: |
          rm -rf *
