name: CI Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DIST_FILE: ivy-website-market.tar

jobs:
  build:
    runs-on: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: browser-actions/setup-chrome@v1

      - name: install dependencies
        run: |
          npm install

      - name: run test
        run: |
          npm run test

      - name: Clean up
        run: |
          rm -rf *
