name: CI Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DIST_FILE: ivy-website-market.tar

jobs:
  build:
    runs-on: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          npm install

      - name: Run test
        run: |
          npm run test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            coverage/**/*.xml

      - name: Clean up
        run: |
          rm -rf *
